---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: ml
  annotations:
    serving.kserve.io/s3-endpoint: s3.amazonaws.com
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: us-east-1
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: AKIA4MI2JKPCAUDSG2PP
  AWS_SECRET_ACCESS_KEY: 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
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-access
  namespace: ml
secrets:
- name: s3-secret
